# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\BaiduNetdiskWorkspace\Research\Swarm\VColCOS_GUI\viewers\communication.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_com(object):
    def setupUi(self, com):
        com.setObjectName("com")
        com.setWindowModality(QtCore.Qt.WindowModal)
        com.resize(620, 743)
        com.setFocusPolicy(QtCore.Qt.NoFocus)
        com.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(19, 126, 124);")
        self.label_8 = QtWidgets.QLabel(com)
        self.label_8.setGeometry(QtCore.QRect(12, 40, 223, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(com)
        self.frame.setGeometry(QtCore.QRect(244, 2, 351, 109))
        self.frame.setStyleSheet("border-image: url(:/resource/resources/communication.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pb_scan_port = QtWidgets.QPushButton(com)
        self.pb_scan_port.setGeometry(QtCore.QRect(14, 212, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_scan_port.setFont(font)
        self.pb_scan_port.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_scan_port.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_scan_port.setObjectName("pb_scan_port")
        self.comboBox_com_port = QtWidgets.QComboBox(com)
        self.comboBox_com_port.setGeometry(QtCore.QRect(16, 182, 111, 23))
        self.comboBox_com_port.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.comboBox_com_port.setObjectName("comboBox_com_port")
        self.label_54 = QtWidgets.QLabel(com)
        self.label_54.setGeometry(QtCore.QRect(14, 158, 67, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.pb_open_port = QtWidgets.QPushButton(com)
        self.pb_open_port.setGeometry(QtCore.QRect(14, 252, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_open_port.setFont(font)
        self.pb_open_port.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_open_port.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_open_port.setObjectName("pb_open_port")
        self.pb_close_port = QtWidgets.QPushButton(com)
        self.pb_close_port.setGeometry(QtCore.QRect(12, 290, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_close_port.setFont(font)
        self.pb_close_port.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_close_port.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_close_port.setObjectName("pb_close_port")
        self.text_edit_recv_raw = QtWidgets.QPlainTextEdit(com)
        self.text_edit_recv_raw.setGeometry(QtCore.QRect(154, 196, 445, 131))
        self.text_edit_recv_raw.setObjectName("text_edit_recv_raw")
        self.text_edit_send_raw = QtWidgets.QPlainTextEdit(com)
        self.text_edit_send_raw.setGeometry(QtCore.QRect(156, 432, 351, 27))
        self.text_edit_send_raw.setObjectName("text_edit_send_raw")
        self.label_23 = QtWidgets.QLabel(com)
        self.label_23.setGeometry(QtCore.QRect(150, 386, 165, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(com)
        self.label_24.setGeometry(QtCore.QRect(150, 156, 167, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.cb_show_raw_hex = QtWidgets.QCheckBox(com)
        self.cb_show_raw_hex.setGeometry(QtCore.QRect(296, 174, 41, 19))
        self.cb_show_raw_hex.setObjectName("cb_show_raw_hex")
        self.cb_show_raw = QtWidgets.QCheckBox(com)
        self.cb_show_raw.setGeometry(QtCore.QRect(156, 174, 105, 19))
        self.cb_show_raw.setObjectName("cb_show_raw")
        self.pb_raw_clear = QtWidgets.QPushButton(com)
        self.pb_raw_clear.setGeometry(QtCore.QRect(536, 172, 57, 21))
        self.pb_raw_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_raw_clear.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_raw_clear.setObjectName("pb_raw_clear")
        self.line_7 = QtWidgets.QFrame(com)
        self.line_7.setGeometry(QtCore.QRect(288, 156, 305, 16))
        self.line_7.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(com)
        self.line_8.setGeometry(QtCore.QRect(262, 386, 341, 16))
        self.line_8.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.pb_raw_send = QtWidgets.QPushButton(com)
        self.pb_raw_send.setGeometry(QtCore.QRect(512, 404, 81, 51))
        self.pb_raw_send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_raw_send.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_raw_send.setObjectName("pb_raw_send")
        self.cb_send_hex = QtWidgets.QCheckBox(com)
        self.cb_send_hex.setGeometry(QtCore.QRect(238, 410, 41, 19))
        self.cb_send_hex.setObjectName("cb_send_hex")
        self.cb_send_newline = QtWidgets.QCheckBox(com)
        self.cb_send_newline.setGeometry(QtCore.QRect(158, 410, 71, 19))
        self.cb_send_newline.setObjectName("cb_send_newline")
        self.label_25 = QtWidgets.QLabel(com)
        self.label_25.setGeometry(QtCore.QRect(150, 536, 165, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.line_9 = QtWidgets.QFrame(com)
        self.line_9.setGeometry(QtCore.QRect(268, 536, 339, 16))
        self.line_9.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.pb_start_capture = QtWidgets.QPushButton(com)
        self.pb_start_capture.setGeometry(QtCore.QRect(16, 382, 109, 69))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_capture.setFont(font)
        self.pb_start_capture.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_start_capture.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_start_capture.setObjectName("pb_start_capture")
        self.pb_clear_cache = QtWidgets.QPushButton(com)
        self.pb_clear_cache.setGeometry(QtCore.QRect(16, 588, 111, 39))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pb_clear_cache.setFont(font)
        self.pb_clear_cache.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_clear_cache.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_clear_cache.setObjectName("pb_clear_cache")
        self.label_43 = QtWidgets.QLabel(com)
        self.label_43.setGeometry(QtCore.QRect(150, 362, 23, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.cbox_send_robot_id = QtWidgets.QComboBox(com)
        self.cbox_send_robot_id.setGeometry(QtCore.QRect(180, 362, 83, 21))
        self.cbox_send_robot_id.setObjectName("cbox_send_robot_id")
        self.cb_send_with_time = QtWidgets.QCheckBox(com)
        self.cb_send_with_time.setGeometry(QtCore.QRect(310, 364, 121, 19))
        self.cb_send_with_time.setChecked(True)
        self.cb_send_with_time.setObjectName("cb_send_with_time")
        self.cb_send_to_all = QtWidgets.QCheckBox(com)
        self.cb_send_to_all.setGeometry(QtCore.QRect(448, 364, 153, 19))
        self.cb_send_to_all.setObjectName("cb_send_to_all")
        self.sp_send_p_5 = QtWidgets.QDoubleSpinBox(com)
        self.sp_send_p_5.setGeometry(QtCore.QRect(358, 494, 79, 16))
        self.sp_send_p_5.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_send_p_5.setMinimum(-9999.0)
        self.sp_send_p_5.setMaximum(9999.99)
        self.sp_send_p_5.setSingleStep(0.01)
        self.sp_send_p_5.setObjectName("sp_send_p_5")
        self.sp_send_p_2 = QtWidgets.QDoubleSpinBox(com)
        self.sp_send_p_2.setGeometry(QtCore.QRect(214, 494, 79, 16))
        self.sp_send_p_2.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_send_p_2.setMinimum(-9999.0)
        self.sp_send_p_2.setMaximum(9999.99)
        self.sp_send_p_2.setSingleStep(0.01)
        self.sp_send_p_2.setObjectName("sp_send_p_2")
        self.cb_send_p_3 = QtWidgets.QCheckBox(com)
        self.cb_send_p_3.setGeometry(QtCore.QRect(158, 516, 51, 15))
        self.cb_send_p_3.setObjectName("cb_send_p_3")
        self.cb_send_p_1 = QtWidgets.QCheckBox(com)
        self.cb_send_p_1.setGeometry(QtCore.QRect(158, 476, 51, 15))
        self.cb_send_p_1.setObjectName("cb_send_p_1")
        self.sp_send_p_3 = QtWidgets.QDoubleSpinBox(com)
        self.sp_send_p_3.setGeometry(QtCore.QRect(214, 514, 79, 16))
        self.sp_send_p_3.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_send_p_3.setMinimum(-9999.0)
        self.sp_send_p_3.setMaximum(9999.99)
        self.sp_send_p_3.setSingleStep(0.01)
        self.sp_send_p_3.setObjectName("sp_send_p_3")
        self.cb_send_p_4 = QtWidgets.QCheckBox(com)
        self.cb_send_p_4.setGeometry(QtCore.QRect(302, 476, 51, 15))
        self.cb_send_p_4.setObjectName("cb_send_p_4")
        self.sp_send_p_1 = QtWidgets.QDoubleSpinBox(com)
        self.sp_send_p_1.setGeometry(QtCore.QRect(214, 475, 79, 16))
        self.sp_send_p_1.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_send_p_1.setMinimum(-9999.0)
        self.sp_send_p_1.setMaximum(9999.99)
        self.sp_send_p_1.setSingleStep(0.01)
        self.sp_send_p_1.setObjectName("sp_send_p_1")
        self.cb_send_p_2 = QtWidgets.QCheckBox(com)
        self.cb_send_p_2.setGeometry(QtCore.QRect(158, 496, 51, 15))
        self.cb_send_p_2.setObjectName("cb_send_p_2")
        self.cb_send_p_5 = QtWidgets.QCheckBox(com)
        self.cb_send_p_5.setGeometry(QtCore.QRect(302, 496, 51, 15))
        self.cb_send_p_5.setObjectName("cb_send_p_5")
        self.sp_send_p_4 = QtWidgets.QDoubleSpinBox(com)
        self.sp_send_p_4.setGeometry(QtCore.QRect(358, 474, 79, 16))
        self.sp_send_p_4.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_send_p_4.setMinimum(-9999.0)
        self.sp_send_p_4.setMaximum(9999.99)
        self.sp_send_p_4.setSingleStep(0.01)
        self.sp_send_p_4.setObjectName("sp_send_p_4")
        self.pb_autosend_update = QtWidgets.QPushButton(com)
        self.pb_autosend_update.setGeometry(QtCore.QRect(512, 476, 79, 55))
        self.pb_autosend_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_autosend_update.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_autosend_update.setObjectName("pb_autosend_update")
        self.cb_send_p_autosend = QtWidgets.QCheckBox(com)
        self.cb_send_p_autosend.setGeometry(QtCore.QRect(432, 408, 71, 21))
        self.cb_send_p_autosend.setObjectName("cb_send_p_autosend")
        self.label_44 = QtWidgets.QLabel(com)
        self.label_44.setGeometry(QtCore.QRect(154, 564, 35, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.sp_motion_speed = QtWidgets.QSpinBox(com)
        self.sp_motion_speed.setGeometry(QtCore.QRect(194, 564, 61, 22))
        self.sp_motion_speed.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_motion_speed.setMinimum(1)
        self.sp_motion_speed.setMaximum(1000)
        self.sp_motion_speed.setSingleStep(2)
        self.sp_motion_speed.setProperty("value", 20)
        self.sp_motion_speed.setDisplayIntegerBase(10)
        self.sp_motion_speed.setObjectName("sp_motion_speed")
        self.label_45 = QtWidgets.QLabel(com)
        self.label_45.setGeometry(QtCore.QRect(154, 592, 35, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.sp_motion_time = QtWidgets.QSpinBox(com)
        self.sp_motion_time.setGeometry(QtCore.QRect(192, 590, 63, 22))
        self.sp_motion_time.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_motion_time.setMinimum(1)
        self.sp_motion_time.setMaximum(1000)
        self.sp_motion_time.setSingleStep(2)
        self.sp_motion_time.setProperty("value", 2)
        self.sp_motion_time.setDisplayIntegerBase(10)
        self.sp_motion_time.setObjectName("sp_motion_time")
        self.pb_motion_start = QtWidgets.QPushButton(com)
        self.pb_motion_start.setGeometry(QtCore.QRect(306, 560, 87, 29))
        self.pb_motion_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_motion_start.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_motion_start.setIconSize(QtCore.QSize(20, 20))
        self.pb_motion_start.setObjectName("pb_motion_start")
        self.pb_motion_stop = QtWidgets.QPushButton(com)
        self.pb_motion_stop.setGeometry(QtCore.QRect(306, 594, 87, 29))
        self.pb_motion_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_motion_stop.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_motion_stop.setIconSize(QtCore.QSize(20, 20))
        self.pb_motion_stop.setObjectName("pb_motion_stop")
        self.pb_motion_forward = QtWidgets.QPushButton(com)
        self.pb_motion_forward.setGeometry(QtCore.QRect(474, 554, 57, 29))
        self.pb_motion_forward.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_motion_forward.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_motion_forward.setIconSize(QtCore.QSize(20, 20))
        self.pb_motion_forward.setObjectName("pb_motion_forward")
        self.pb_motion_left = QtWidgets.QPushButton(com)
        self.pb_motion_left.setGeometry(QtCore.QRect(410, 576, 55, 29))
        self.pb_motion_left.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_motion_left.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_motion_left.setIconSize(QtCore.QSize(20, 20))
        self.pb_motion_left.setObjectName("pb_motion_left")
        self.pb_motion_backward = QtWidgets.QPushButton(com)
        self.pb_motion_backward.setGeometry(QtCore.QRect(474, 596, 55, 29))
        self.pb_motion_backward.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_motion_backward.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_motion_backward.setIconSize(QtCore.QSize(20, 20))
        self.pb_motion_backward.setObjectName("pb_motion_backward")
        self.pb_motion_right = QtWidgets.QPushButton(com)
        self.pb_motion_right.setGeometry(QtCore.QRect(538, 574, 55, 29))
        self.pb_motion_right.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_motion_right.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_motion_right.setIconSize(QtCore.QSize(20, 20))
        self.pb_motion_right.setObjectName("pb_motion_right")
        self.line_12 = QtWidgets.QFrame(com)
        self.line_12.setGeometry(QtCore.QRect(326, 132, 273, 16))
        self.line_12.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(4)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.label_9 = QtWidgets.QLabel(com)
        self.label_9.setGeometry(QtCore.QRect(144, 126, 183, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_14 = QtWidgets.QFrame(com)
        self.line_14.setGeometry(QtCore.QRect(324, 340, 279, 16))
        self.line_14.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(4)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.label_10 = QtWidgets.QLabel(com)
        self.label_10.setGeometry(QtCore.QRect(144, 334, 181, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.line_15 = QtWidgets.QFrame(com)
        self.line_15.setGeometry(QtCore.QRect(136, 158, 7, 473))
        self.line_15.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setObjectName("line_15")
        self.label_11 = QtWidgets.QLabel(com)
        self.label_11.setGeometry(QtCore.QRect(12, 126, 87, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.line_13 = QtWidgets.QFrame(com)
        self.line_13.setGeometry(QtCore.QRect(82, 126, 53, 25))
        self.line_13.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(4)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setObjectName("line_13")
        self.label_6 = QtWidgets.QLabel(com)
        self.label_6.setGeometry(QtCore.QRect(18, 464, 109, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.sp_num_packs = QtWidgets.QSpinBox(com)
        self.sp_num_packs.setGeometry(QtCore.QRect(50, 487, 77, 21))
        self.sp_num_packs.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_num_packs.setMinimum(1)
        self.sp_num_packs.setMaximum(255)
        self.sp_num_packs.setSingleStep(2)
        self.sp_num_packs.setProperty("value", 5)
        self.sp_num_packs.setDisplayIntegerBase(10)
        self.sp_num_packs.setObjectName("sp_num_packs")
        self.label_46 = QtWidgets.QLabel(com)
        self.label_46.setGeometry(QtCore.QRect(16, 510, 23, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.cbox_request_id = QtWidgets.QComboBox(com)
        self.cbox_request_id.setGeometry(QtCore.QRect(50, 510, 75, 21))
        self.cbox_request_id.setObjectName("cbox_request_id")
        self.cb_request_all = QtWidgets.QCheckBox(com)
        self.cb_request_all.setGeometry(QtCore.QRect(18, 536, 111, 19))
        self.cb_request_all.setObjectName("cb_request_all")
        self.pb_request_update = QtWidgets.QPushButton(com)
        self.pb_request_update.setGeometry(QtCore.QRect(18, 560, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_request_update.setFont(font)
        self.pb_request_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_request_update.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_request_update.setObjectName("pb_request_update")
        self.pb_request_update_2 = QtWidgets.QPushButton(com)
        self.pb_request_update_2.setGeometry(QtCore.QRect(16, 348, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_request_update_2.setFont(font)
        self.pb_request_update_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_request_update_2.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_request_update_2.setObjectName("pb_request_update_2")
        self.cb_send_p_6 = QtWidgets.QCheckBox(com)
        self.cb_send_p_6.setGeometry(QtCore.QRect(302, 514, 51, 15))
        self.cb_send_p_6.setObjectName("cb_send_p_6")
        self.sp_send_p_6 = QtWidgets.QDoubleSpinBox(com)
        self.sp_send_p_6.setGeometry(QtCore.QRect(358, 514, 79, 16))
        self.sp_send_p_6.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_send_p_6.setMinimum(-9999.0)
        self.sp_send_p_6.setMaximum(9999.99)
        self.sp_send_p_6.setSingleStep(0.01)
        self.sp_send_p_6.setObjectName("sp_send_p_6")
        self.line_10 = QtWidgets.QFrame(com)
        self.line_10.setGeometry(QtCore.QRect(158, 460, 437, 16))
        self.line_10.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setLineWidth(1)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.et_data_flow_info = QtWidgets.QLabel(com)
        self.et_data_flow_info.setGeometry(QtCore.QRect(18, 654, 581, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.et_data_flow_info.setFont(font)
        self.et_data_flow_info.setStyleSheet("color: rgb(19, 126, 124);\n"
"border-top-color: rgb(0, 0, 0);")
        self.et_data_flow_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.et_data_flow_info.setText("")
        self.et_data_flow_info.setObjectName("et_data_flow_info")
        self.line_16 = QtWidgets.QFrame(com)
        self.line_16.setGeometry(QtCore.QRect(14, 634, 591, 16))
        self.line_16.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setLineWidth(4)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.text_edit_com_info = QtWidgets.QTextEdit(com)
        self.text_edit_com_info.setGeometry(QtCore.QRect(16, 678, 585, 57))
        self.text_edit_com_info.setReadOnly(True)
        self.text_edit_com_info.setObjectName("text_edit_com_info")

        self.retranslateUi(com)
        self.comboBox_com_port.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(com)

    def retranslateUi(self, com):
        _translate = QtCore.QCoreApplication.translate
        com.setWindowTitle(_translate("com", "VColCOSP-CommunicationPanel"))
        self.label_8.setText(_translate("com", "VColCOSP - Communication"))
        self.pb_scan_port.setText(_translate("com", "Scan Port"))
        self.label_54.setText(_translate("com", "Port:"))
        self.pb_open_port.setText(_translate("com", "Open Port"))
        self.pb_close_port.setText(_translate("com", "Close Port"))
        self.label_23.setText(_translate("com", "| Raw Data Send"))
        self.label_24.setText(_translate("com", "| Raw Data Received"))
        self.cb_show_raw_hex.setText(_translate("com", "Hex"))
        self.cb_show_raw.setText(_translate("com", "show raw data"))
        self.pb_raw_clear.setText(_translate("com", "CLEAR"))
        self.pb_raw_send.setText(_translate("com", "SEND"))
        self.cb_send_hex.setToolTip(_translate("com", "<html><head/><body><p>type in hex form: </p><p><span style=\" font-weight:600;\">78 ef ad</span></p></body></html>"))
        self.cb_send_hex.setText(_translate("com", "Hex"))
        self.cb_send_newline.setText(_translate("com", "New Line"))
        self.label_25.setText(_translate("com", "| Motion Control"))
        self.pb_start_capture.setText(_translate("com", "Start \n"
" Capture"))
        self.pb_clear_cache.setText(_translate("com", "Clear \n"
" Data Cache"))
        self.label_43.setText(_translate("com", "ID:"))
        self.cb_send_with_time.setText(_translate("com", "With TimeStamp"))
        self.cb_send_to_all.setText(_translate("com", "To All ID(broadcast)"))
        self.cb_send_p_3.setText(_translate("com", "P_CH3"))
        self.cb_send_p_1.setText(_translate("com", "P_CH1"))
        self.cb_send_p_4.setText(_translate("com", "P_CH4"))
        self.cb_send_p_2.setText(_translate("com", "P_CH2"))
        self.cb_send_p_5.setText(_translate("com", "P_CH5"))
        self.pb_autosend_update.setText(_translate("com", "UPDATE"))
        self.cb_send_p_autosend.setToolTip(_translate("com", "<html><head/><body><p>when the data in CH1-CH5 changed,data will be automatically sended if checked.</p></body></html>"))
        self.cb_send_p_autosend.setText(_translate("com", "AutoSend"))
        self.label_44.setText(_translate("com", "Speed"))
        self.label_45.setText(_translate("com", "Time"))
        self.pb_motion_start.setText(_translate("com", "Start"))
        self.pb_motion_stop.setText(_translate("com", "Stop"))
        self.pb_motion_forward.setText(_translate("com", "↑"))
        self.pb_motion_left.setText(_translate("com", "←"))
        self.pb_motion_backward.setText(_translate("com", "↓"))
        self.pb_motion_right.setText(_translate("com", "→"))
        self.label_9.setText(_translate("com", "Robots →→→→  Host"))
        self.label_10.setText(_translate("com", " Host →→→→  Robots"))
        self.label_11.setText(_translate("com", "Settings"))
        self.label_6.setText(_translate("com", "Num Packets:"))
        self.sp_num_packs.setToolTip(_translate("com", "<html><head/><body><p>0-255, <span style=\" font-weight:600; font-style:italic; color:#ff0000;\">0</span> means <span style=\" color:#ff0000;\">stop</span> getting data, <span style=\" font-weight:600; font-style:italic; color:#ffaa00;\">255</span> means <span style=\" color:#ffaa00;\">continously</span> getting data from robot</p></body></html>"))
        self.label_46.setText(_translate("com", "ID:"))
        self.cb_request_all.setText(_translate("com", "Request All"))
        self.pb_request_update.setText(_translate("com", "Request Update"))
        self.pb_request_update_2.setText(_translate("com", "Protocol"))
        self.cb_send_p_6.setText(_translate("com", "P_CH6"))
import resources_rc
