# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\BaiduNetdiskWorkspace\Research\Swarm\VColCOS_GUI\viewers\data_save_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataSavingSetting(object):
    def setupUi(self, DataSavingSetting):
        DataSavingSetting.setObjectName("DataSavingSetting")
        DataSavingSetting.resize(630, 644)
        DataSavingSetting.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(19, 126, 124);")
        self.spinBox_time_interval = QtWidgets.QSpinBox(DataSavingSetting)
        self.spinBox_time_interval.setGeometry(QtCore.QRect(336, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_time_interval.setFont(font)
        self.spinBox_time_interval.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.spinBox_time_interval.setMaximum(2000)
        self.spinBox_time_interval.setProperty("value", 500)
        self.spinBox_time_interval.setObjectName("spinBox_time_interval")
        self.gridLayoutWidget = QtWidgets.QWidget(DataSavingSetting)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(42, 292, 555, 293))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_data = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_data.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_data.setObjectName("gridLayout_data")
        self.cbox_file_type = QtWidgets.QComboBox(DataSavingSetting)
        self.cbox_file_type.setGeometry(QtCore.QRect(96, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbox_file_type.setFont(font)
        self.cbox_file_type.setObjectName("cbox_file_type")
        self.cbox_file_type.addItem("")
        self.cbox_file_type.addItem("")
        self.cbox_file_type.addItem("")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(DataSavingSetting)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(38, 110, 559, 119))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_id = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_id.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_id.setObjectName("gridLayout_id")
        self.pushButton_cancel = QtWidgets.QPushButton(DataSavingSetting)
        self.pushButton_cancel.setGeometry(QtCore.QRect(500, 610, 91, 23))
        self.pushButton_cancel.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label = QtWidgets.QLabel(DataSavingSetting)
        self.label.setGeometry(QtCore.QRect(36, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_all_data = QtWidgets.QPushButton(DataSavingSetting)
        self.pushButton_all_data.setGeometry(QtCore.QRect(518, 248, 81, 21))
        self.pushButton_all_data.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_all_data.setObjectName("pushButton_all_data")
        self.pushButton_ok = QtWidgets.QPushButton(DataSavingSetting)
        self.pushButton_ok.setGeometry(QtCore.QRect(396, 610, 91, 23))
        self.pushButton_ok.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_all_robot = QtWidgets.QPushButton(DataSavingSetting)
        self.pushButton_all_robot.setGeometry(QtCore.QRect(522, 66, 81, 21))
        self.pushButton_all_robot.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pushButton_all_robot.setObjectName("pushButton_all_robot")
        self.line_2 = QtWidgets.QFrame(DataSavingSetting)
        self.line_2.setGeometry(QtCore.QRect(102, 90, 497, 20))
        self.line_2.setStyleSheet("color: rgb(85, 85, 255);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(DataSavingSetting)
        self.label_2.setGeometry(QtCore.QRect(226, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(DataSavingSetting)
        self.label_6.setGeometry(QtCore.QRect(40, 268, 39, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_6.setObjectName("label_6")
        self.line_5 = QtWidgets.QFrame(DataSavingSetting)
        self.line_5.setGeometry(QtCore.QRect(76, 270, 523, 20))
        self.line_5.setStyleSheet("color:rgb(255, 85, 0)")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.label_4 = QtWidgets.QLabel(DataSavingSetting)
        self.label_4.setGeometry(QtCore.QRect(424, 30, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(DataSavingSetting)
        self.label_3.setGeometry(QtCore.QRect(388, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox_max_data_length = QtWidgets.QSpinBox(DataSavingSetting)
        self.spinBox_max_data_length.setGeometry(QtCore.QRect(514, 30, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_max_data_length.setFont(font)
        self.spinBox_max_data_length.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.spinBox_max_data_length.setMaximum(2000)
        self.spinBox_max_data_length.setProperty("value", 500)
        self.spinBox_max_data_length.setObjectName("spinBox_max_data_length")
        self.label_5 = QtWidgets.QLabel(DataSavingSetting)
        self.label_5.setGeometry(QtCore.QRect(40, 88, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(DataSavingSetting)
        self.line_3.setGeometry(QtCore.QRect(38, 226, 561, 20))
        self.line_3.setStyleSheet("color: rgb(85, 85, 255);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_6 = QtWidgets.QFrame(DataSavingSetting)
        self.line_6.setGeometry(QtCore.QRect(40, 582, 559, 20))
        self.line_6.setStyleSheet("color:rgb(255, 85, 0)")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")

        self.retranslateUi(DataSavingSetting)
        QtCore.QMetaObject.connectSlotsByName(DataSavingSetting)

    def retranslateUi(self, DataSavingSetting):
        _translate = QtCore.QCoreApplication.translate
        DataSavingSetting.setWindowTitle(_translate("DataSavingSetting", "VColCOSP-DataSavingSetting"))
        self.cbox_file_type.setItemText(0, _translate("DataSavingSetting", ".mat"))
        self.cbox_file_type.setItemText(1, _translate("DataSavingSetting", ".txt"))
        self.cbox_file_type.setItemText(2, _translate("DataSavingSetting", ".csv"))
        self.pushButton_cancel.setText(_translate("DataSavingSetting", "Cancel"))
        self.label.setText(_translate("DataSavingSetting", "File Type"))
        self.pushButton_all_data.setText(_translate("DataSavingSetting", "All DATA"))
        self.pushButton_ok.setText(_translate("DataSavingSetting", "OK"))
        self.pushButton_all_robot.setText(_translate("DataSavingSetting", "All ROBOT"))
        self.label_2.setText(_translate("DataSavingSetting", "Save Time Interval"))
        self.label_6.setText(_translate("DataSavingSetting", "Data"))
        self.label_4.setText(_translate("DataSavingSetting", "Max data length"))
        self.label_3.setText(_translate("DataSavingSetting", "ms"))
        self.label_5.setText(_translate("DataSavingSetting", "Robot ID"))
