# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\BaiduNetdiskWorkspace\Research\Swarm\VColCOS_GUI\viewers\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Login.setFont(font)
        Login.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(170, 170, 255);")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(0, 20, 640, 271))
        self.frame.setStyleSheet("border-image: url(:/resource/resources/login_background.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_close = QtWidgets.QPushButton(Login)
        self.pushButton_close.setGeometry(QtCore.QRect(620, 0, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 0, 0);")
        self.pushButton_close.setObjectName("pushButton_close")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(80, 327, 30, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/resource/resources/icon_user.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.t_user_name = QtWidgets.QTextEdit(Login)
        self.t_user_name.setGeometry(QtCore.QRect(150, 320, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.t_user_name.setFont(font)
        self.t_user_name.setStyleSheet("border:3px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"color: rgb(255, 255, 255);")
        self.t_user_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t_user_name.setLineWidth(6)
        self.t_user_name.setObjectName("t_user_name")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(70, 395, 60, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/resource/resources/icon_key.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.t_password = QtWidgets.QTextEdit(Login)
        self.t_password.setGeometry(QtCore.QRect(150, 390, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.t_password.setFont(font)
        self.t_password.setStyleSheet("border:3px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"color: rgb(255, 255, 255);")
        self.t_password.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t_password.setLineWidth(6)
        self.t_password.setObjectName("t_password")
        self.pushButton_login = QtWidgets.QPushButton(Login)
        self.pushButton_login.setGeometry(QtCore.QRect(590, 440, 41, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_login.setStyleSheet("\n"
"border-radius:10px;\n"
"")
        self.pushButton_login.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/resources/icon_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_login.setIcon(icon)
        self.pushButton_login.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_login.setFlat(False)
        self.pushButton_login.setObjectName("pushButton_login")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "VColCOSP V1.0 Login"))
        self.pushButton_close.setText(_translate("Login", "X"))
        self.pushButton_login.setToolTip(_translate("Login", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#137e7c;\">Login</span></p></body></html>"))
import resources_rc
