# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\VColCOSP_GUI\viewers\main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_menu(object):
    def setupUi(self, main_menu):
        main_menu.setObjectName("main_menu")
        main_menu.resize(640, 584)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        main_menu.setFont(font)
        main_menu.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(19, 126, 124);")
        self.pb_loc = QtWidgets.QPushButton(main_menu)
        self.pb_loc.setGeometry(QtCore.QRect(8, 60, 140, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_loc.setFont(font)
        self.pb_loc.setStyleSheet("QPushButton::disabled {\n"
"    border: 4px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 4px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_loc.setObjectName("pb_loc")
        self.pb_phero = QtWidgets.QPushButton(main_menu)
        self.pb_phero.setGeometry(QtCore.QRect(476, 60, 140, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_phero.setFont(font)
        self.pb_phero.setStyleSheet("QPushButton::disabled {\n"
"    border: 4px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 4px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_phero.setObjectName("pb_phero")
        self.pb_com = QtWidgets.QPushButton(main_menu)
        self.pb_com.setGeometry(QtCore.QRect(320, 60, 140, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_com.setFont(font)
        self.pb_com.setStyleSheet("border: 4px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_com.setObjectName("pb_com")
        self.pb_vscene = QtWidgets.QPushButton(main_menu)
        self.pb_vscene.setGeometry(QtCore.QRect(164, 60, 140, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_vscene.setFont(font)
        self.pb_vscene.setStyleSheet("QPushButton::disabled {\n"
"    border: 4px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 4px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_vscene.setObjectName("pb_vscene")
        self.text_edit_sys_info = QtWidgets.QTextEdit(main_menu)
        self.text_edit_sys_info.setGeometry(QtCore.QRect(6, 174, 621, 97))
        self.text_edit_sys_info.setReadOnly(True)
        self.text_edit_sys_info.setObjectName("text_edit_sys_info")
        self.et_sys_timer = QtWidgets.QLabel(main_menu)
        self.et_sys_timer.setGeometry(QtCore.QRect(6, 144, 621, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.et_sys_timer.setFont(font)
        self.et_sys_timer.setStyleSheet("color: rgb(19, 126, 124);\n"
"border-top-color: rgb(0, 0, 0);")
        self.et_sys_timer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.et_sys_timer.setObjectName("et_sys_timer")
        self.et_welcome = QtWidgets.QLabel(main_menu)
        self.et_welcome.setGeometry(QtCore.QRect(10, 20, 621, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.et_welcome.setFont(font)
        self.et_welcome.setStyleSheet("color: rgb(19, 126, 124);\n"
"border-top-color: rgb(0, 0, 0);")
        self.et_welcome.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.et_welcome.setObjectName("et_welcome")
        self.label_11 = QtWidgets.QLabel(main_menu)
        self.label_11.setGeometry(QtCore.QRect(254, 274, 125, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.line_13 = QtWidgets.QFrame(main_menu)
        self.line_13.setGeometry(QtCore.QRect(378, 274, 251, 25))
        self.line_13.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setLineWidth(4)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(main_menu)
        self.line_14.setGeometry(QtCore.QRect(6, 274, 247, 25))
        self.line_14.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setLineWidth(4)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.pb_start_exp = QtWidgets.QPushButton(main_menu)
        self.pb_start_exp.setGeometry(QtCore.QRect(110, 410, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_exp.setFont(font)
        self.pb_start_exp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_start_exp.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_start_exp.setObjectName("pb_start_exp")
        self.label_54 = QtWidgets.QLabel(main_menu)
        self.label_54.setGeometry(QtCore.QRect(18, 310, 67, 20))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.lineEdit_exp_name = QtWidgets.QLineEdit(main_menu)
        self.lineEdit_exp_name.setGeometry(QtCore.QRect(84, 310, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_exp_name.setFont(font)
        self.lineEdit_exp_name.setObjectName("lineEdit_exp_name")
        self.label_55 = QtWidgets.QLabel(main_menu)
        self.label_55.setGeometry(QtCore.QRect(18, 340, 147, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.pb_save_data_setting = QtWidgets.QPushButton(main_menu)
        self.pb_save_data_setting.setGeometry(QtCore.QRect(350, 338, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_data_setting.setFont(font)
        self.pb_save_data_setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_save_data_setting.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_save_data_setting.setObjectName("pb_save_data_setting")
        self.pb_save_data = QtWidgets.QPushButton(main_menu)
        self.pb_save_data.setGeometry(QtCore.QRect(526, 356, 91, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_data.setFont(font)
        self.pb_save_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_save_data.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_save_data.setObjectName("pb_save_data")
        self.text_edit_exp_info = QtWidgets.QTextEdit(main_menu)
        self.text_edit_exp_info.setGeometry(QtCore.QRect(14, 506, 611, 67))
        self.text_edit_exp_info.setReadOnly(True)
        self.text_edit_exp_info.setObjectName("text_edit_exp_info")
        self.et_exp_timer = QtWidgets.QLabel(main_menu)
        self.et_exp_timer.setGeometry(QtCore.QRect(16, 482, 607, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.et_exp_timer.setFont(font)
        self.et_exp_timer.setStyleSheet("color: rgb(19, 126, 124);\n"
"border-top-color: rgb(0, 0, 0);")
        self.et_exp_timer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.et_exp_timer.setObjectName("et_exp_timer")
        self.pb_add_map = QtWidgets.QPushButton(main_menu)
        self.pb_add_map.setGeometry(QtCore.QRect(434, 418, 81, 29))
        self.pb_add_map.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_add_map.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/resources/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_add_map.setIcon(icon)
        self.pb_add_map.setIconSize(QtCore.QSize(20, 20))
        self.pb_add_map.setObjectName("pb_add_map")
        self.pb_add_distribution = QtWidgets.QPushButton(main_menu)
        self.pb_add_distribution.setGeometry(QtCore.QRect(344, 454, 173, 29))
        self.pb_add_distribution.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_add_distribution.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resource/resources/distribution.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_add_distribution.setIcon(icon1)
        self.pb_add_distribution.setIconSize(QtCore.QSize(20, 20))
        self.pb_add_distribution.setObjectName("pb_add_distribution")
        self.pb_destroy_figure = QtWidgets.QPushButton(main_menu)
        self.pb_destroy_figure.setGeometry(QtCore.QRect(532, 418, 81, 63))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_destroy_figure.setFont(font)
        self.pb_destroy_figure.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_destroy_figure.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        self.pb_destroy_figure.setObjectName("pb_destroy_figure")
        self.pb_add_plot = QtWidgets.QPushButton(main_menu)
        self.pb_add_plot.setGeometry(QtCore.QRect(344, 418, 79, 29))
        self.pb_add_plot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_add_plot.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:4px;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resource/resources/plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_add_plot.setIcon(icon2)
        self.pb_add_plot.setIconSize(QtCore.QSize(20, 20))
        self.pb_add_plot.setObjectName("pb_add_plot")
        self.line_11 = QtWidgets.QFrame(main_menu)
        self.line_11.setGeometry(QtCore.QRect(492, 396, 133, 16))
        self.line_11.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.label_27 = QtWidgets.QLabel(main_menu)
        self.label_27.setGeometry(QtCore.QRect(344, 396, 141, 16))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(main_menu)
        self.label_28.setGeometry(QtCore.QRect(342, 312, 141, 16))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.line_12 = QtWidgets.QFrame(main_menu)
        self.line_12.setGeometry(QtCore.QRect(442, 312, 183, 16))
        self.line_12.setStyleSheet("color: rgb(19, 126, 124);")
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.cb_auto_save = QtWidgets.QCheckBox(main_menu)
        self.cb_auto_save.setGeometry(QtCore.QRect(532, 332, 81, 20))
        self.cb_auto_save.setObjectName("cb_auto_save")
        self.pb_load_config = QtWidgets.QPushButton(main_menu)
        self.pb_load_config.setGeometry(QtCore.QRect(8, 408, 91, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_load_config.setFont(font)
        self.pb_load_config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_load_config.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_load_config.setObjectName("pb_load_config")
        self.pb_save_config = QtWidgets.QPushButton(main_menu)
        self.pb_save_config.setGeometry(QtCore.QRect(10, 450, 91, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_config.setFont(font)
        self.pb_save_config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_save_config.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_save_config.setObjectName("pb_save_config")
        self.label_56 = QtWidgets.QLabel(main_menu)
        self.label_56.setGeometry(QtCore.QRect(230, 340, 21, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.sp_exp_task_interval = QtWidgets.QDoubleSpinBox(main_menu)
        self.sp_exp_task_interval.setGeometry(QtCore.QRect(180, 340, 51, 31))
        self.sp_exp_task_interval.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(0,255, 0);\n"
"")
        self.sp_exp_task_interval.setProperty("value", 1.0)
        self.sp_exp_task_interval.setObjectName("sp_exp_task_interval")
        self.cb_exp_data_plot = QtWidgets.QCheckBox(main_menu)
        self.cb_exp_data_plot.setGeometry(QtCore.QRect(20, 380, 231, 19))
        self.cb_exp_data_plot.setObjectName("cb_exp_data_plot")
        self.pb_reset_exp = QtWidgets.QPushButton(main_menu)
        self.pb_reset_exp.setGeometry(QtCore.QRect(210, 410, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_reset_exp.setFont(font)
        self.pb_reset_exp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_reset_exp.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_reset_exp.setObjectName("pb_reset_exp")
        self.pb_save_data_clear_cache = QtWidgets.QPushButton(main_menu)
        self.pb_save_data_clear_cache.setGeometry(QtCore.QRect(430, 340, 81, 49))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_save_data_clear_cache.setFont(font)
        self.pb_save_data_clear_cache.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_save_data_clear_cache.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_save_data_clear_cache.setObjectName("pb_save_data_clear_cache")

        self.retranslateUi(main_menu)
        QtCore.QMetaObject.connectSlotsByName(main_menu)

    def retranslateUi(self, main_menu):
        _translate = QtCore.QCoreApplication.translate
        main_menu.setWindowTitle(_translate("main_menu", "VColCOSP-Main Menu"))
        self.pb_loc.setText(_translate("main_menu", "Localization"))
        self.pb_phero.setText(_translate("main_menu", "Pheromone"))
        self.pb_com.setText(_translate("main_menu", "Communication"))
        self.pb_vscene.setText(_translate("main_menu", "Visual Scene"))
        self.et_sys_timer.setText(_translate("main_menu", "Timer"))
        self.et_welcome.setText(_translate("main_menu", "Welcome to VColCOSP, "))
        self.label_11.setText(_translate("main_menu", "Experiment"))
        self.pb_start_exp.setText(_translate("main_menu", "Start \n"
" Experiment"))
        self.label_54.setText(_translate("main_menu", "Name:"))
        self.lineEdit_exp_name.setText(_translate("main_menu", "sample"))
        self.label_55.setText(_translate("main_menu", "Task Time Interval"))
        self.pb_save_data_setting.setText(_translate("main_menu", "Settings"))
        self.pb_save_data.setText(_translate("main_menu", "Save Data"))
        self.et_exp_timer.setText(_translate("main_menu", "Timer"))
        self.pb_add_map.setText(_translate("main_menu", "+ Map"))
        self.pb_add_distribution.setText(_translate("main_menu", "+ Distribution"))
        self.pb_destroy_figure.setText(_translate("main_menu", "Destroy All"))
        self.pb_add_plot.setText(_translate("main_menu", "+ Plot"))
        self.label_27.setText(_translate("main_menu", "| Data Visualization"))
        self.label_28.setText(_translate("main_menu", "| Data Saving"))
        self.cb_auto_save.setText(_translate("main_menu", "Auto Save"))
        self.pb_load_config.setText(_translate("main_menu", "Load Config"))
        self.pb_save_config.setText(_translate("main_menu", "Save Config"))
        self.label_56.setText(_translate("main_menu", "s"))
        self.cb_exp_data_plot.setText(_translate("main_menu", "experiment data visulization"))
        self.pb_reset_exp.setText(_translate("main_menu", "Reset \n"
" Experiment"))
        self.pb_save_data_clear_cache.setText(_translate("main_menu", "Clear \n"
" Cache"))
import resources_rc
