# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\BaiduNetdiskWorkspace\Research\Swarm\VColCOS_GUI\viewers\main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_menu(object):
    def setupUi(self, main_menu):
        main_menu.setObjectName("main_menu")
        main_menu.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        main_menu.setFont(font)
        main_menu.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(19, 126, 124);")
        self.pb_loc = QtWidgets.QPushButton(main_menu)
        self.pb_loc.setGeometry(QtCore.QRect(140, 100, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_loc.setFont(font)
        self.pb_loc.setStyleSheet("border: 4px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_loc.setObjectName("pb_loc")
        self.pb_phero = QtWidgets.QPushButton(main_menu)
        self.pb_phero.setGeometry(QtCore.QRect(140, 240, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_phero.setFont(font)
        self.pb_phero.setStyleSheet("QPushButton::disabled {\n"
"    border: 4px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 4px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_phero.setObjectName("pb_phero")
        self.pb_com = QtWidgets.QPushButton(main_menu)
        self.pb_com.setGeometry(QtCore.QRect(320, 240, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_com.setFont(font)
        self.pb_com.setStyleSheet("border: 4px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_com.setObjectName("pb_com")
        self.pb_vscene = QtWidgets.QPushButton(main_menu)
        self.pb_vscene.setGeometry(QtCore.QRect(320, 100, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_vscene.setFont(font)
        self.pb_vscene.setStyleSheet("QPushButton::disabled {\n"
"    border: 4px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 4px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_vscene.setObjectName("pb_vscene")
        self.text_edit_sys_info = QtWidgets.QTextEdit(main_menu)
        self.text_edit_sys_info.setGeometry(QtCore.QRect(10, 380, 621, 81))
        self.text_edit_sys_info.setReadOnly(True)
        self.text_edit_sys_info.setObjectName("text_edit_sys_info")
        self.et_time = QtWidgets.QLabel(main_menu)
        self.et_time.setGeometry(QtCore.QRect(10, 350, 621, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.et_time.setFont(font)
        self.et_time.setStyleSheet("color: rgb(19, 126, 124);\n"
"border-top-color: rgb(0, 0, 0);")
        self.et_time.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.et_time.setObjectName("et_time")
        self.et_welcome = QtWidgets.QLabel(main_menu)
        self.et_welcome.setGeometry(QtCore.QRect(10, 20, 621, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.et_welcome.setFont(font)
        self.et_welcome.setStyleSheet("color: rgb(19, 126, 124);\n"
"border-top-color: rgb(0, 0, 0);")
        self.et_welcome.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.et_welcome.setObjectName("et_welcome")

        self.retranslateUi(main_menu)
        QtCore.QMetaObject.connectSlotsByName(main_menu)

    def retranslateUi(self, main_menu):
        _translate = QtCore.QCoreApplication.translate
        main_menu.setWindowTitle(_translate("main_menu", "VColCOSP-Main Menu"))
        self.pb_loc.setText(_translate("main_menu", "Localization"))
        self.pb_phero.setText(_translate("main_menu", "Pheromone"))
        self.pb_com.setText(_translate("main_menu", "Communication"))
        self.pb_vscene.setText(_translate("main_menu", "Visual Scene"))
        self.et_time.setText(_translate("main_menu", "Timer"))
        self.et_welcome.setText(_translate("main_menu", "Welcome to VColCOSP, "))
