# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\BaiduNetdiskWorkspace\Research\Swarm\VColCOS_GUI\viewers\message_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_message(object):
    def setupUi(self, message):
        message.setObjectName("message")
        message.resize(454, 212)
        message.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(19, 126, 124);")
        self.pb_ok = QtWidgets.QPushButton(message)
        self.pb_ok.setGeometry(QtCore.QRect(280, 168, 73, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_ok.setFont(font)
        self.pb_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_ok.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_ok.setObjectName("pb_ok")
        self.pb_cancel = QtWidgets.QPushButton(message)
        self.pb_cancel.setGeometry(QtCore.QRect(366, 168, 73, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_cancel.setFont(font)
        self.pb_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pb_cancel.setStyleSheet("QPushButton::disabled {\n"
"    border: 2px solid rgb(149, 149, 149);\n"
"    color:rgb(149, 149, 149);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton{\n"
"border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.pb_cancel.setObjectName("pb_cancel")
        self.textEdit = QtWidgets.QTextEdit(message)
        self.textEdit.setGeometry(QtCore.QRect(110, 26, 327, 133))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border:0 solid #fff")
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setLineWidth(1)
        self.textEdit.setObjectName("textEdit")
        self.frame = QtWidgets.QFrame(message)
        self.frame.setGeometry(QtCore.QRect(18, 56, 73, 75))
        self.frame.setStyleSheet("border-image: url(:/resource/resources/localization.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.retranslateUi(message)
        QtCore.QMetaObject.connectSlotsByName(message)

    def retranslateUi(self, message):
        _translate = QtCore.QCoreApplication.translate
        message.setWindowTitle(_translate("message", "Form"))
        self.pb_ok.setText(_translate("message", "OK"))
        self.pb_cancel.setText(_translate("message", "CANCEL"))
