# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\WorkSpace\VColCOSP_GUI\viewers\phero_bg_info_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_phero_bg_info_setting(object):
    def setupUi(self, phero_bg_info_setting):
        phero_bg_info_setting.setObjectName("phero_bg_info_setting")
        phero_bg_info_setting.resize(274, 467)
        phero_bg_info_setting.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(19, 126, 124);")
        self.groupBox_pos_text = QtWidgets.QGroupBox(phero_bg_info_setting)
        self.groupBox_pos_text.setGeometry(QtCore.QRect(20, 60, 241, 71))
        self.groupBox_pos_text.setStyleSheet("QGroupBox::indicator:unchecked{\n"
"    border: 1px solid rgb(100,100,100);\n"
"    background-color:rgb(100,100,100);\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid rgb(19, 126, 124);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.groupBox_pos_text.setFlat(False)
        self.groupBox_pos_text.setCheckable(True)
        self.groupBox_pos_text.setChecked(False)
        self.groupBox_pos_text.setObjectName("groupBox_pos_text")
        self.pb_pos_text_color = QtWidgets.QPushButton(self.groupBox_pos_text)
        self.pb_pos_text_color.setGeometry(QtCore.QRect(20, 20, 121, 21))
        self.pb_pos_text_color.setStyleSheet("border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_pos_text_color.setObjectName("pb_pos_text_color")
        self.lv_pos_text = QtWidgets.QLabel(self.groupBox_pos_text)
        self.lv_pos_text.setGeometry(QtCore.QRect(180, 10, 51, 51))
        self.lv_pos_text.setText("")
        self.lv_pos_text.setObjectName("lv_pos_text")
        self.sb_pos_text_width = QtWidgets.QSpinBox(self.groupBox_pos_text)
        self.sb_pos_text_width.setGeometry(QtCore.QRect(70, 50, 71, 16))
        self.sb_pos_text_width.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.sb_pos_text_width.setMaximum(100)
        self.sb_pos_text_width.setProperty("value", 2)
        self.sb_pos_text_width.setDisplayIntegerBase(10)
        self.sb_pos_text_width.setObjectName("sb_pos_text_width")
        self.label_16 = QtWidgets.QLabel(self.groupBox_pos_text)
        self.label_16.setGeometry(QtCore.QRect(20, 46, 51, 20))
        self.label_16.setObjectName("label_16")
        self.groupBox_pos_cline = QtWidgets.QGroupBox(phero_bg_info_setting)
        self.groupBox_pos_cline.setGeometry(QtCore.QRect(20, 150, 241, 71))
        self.groupBox_pos_cline.setStyleSheet("QGroupBox::indicator:unchecked{\n"
"    border: 1px solid rgb(100,100,100);\n"
"    background-color:rgb(100,100,100);\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid rgb(19, 126, 124);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.groupBox_pos_cline.setFlat(False)
        self.groupBox_pos_cline.setCheckable(True)
        self.groupBox_pos_cline.setChecked(False)
        self.groupBox_pos_cline.setObjectName("groupBox_pos_cline")
        self.sb_pos_line_width = QtWidgets.QSpinBox(self.groupBox_pos_cline)
        self.sb_pos_line_width.setGeometry(QtCore.QRect(70, 40, 41, 16))
        self.sb_pos_line_width.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.sb_pos_line_width.setMaximum(100)
        self.sb_pos_line_width.setProperty("value", 2)
        self.sb_pos_line_width.setDisplayIntegerBase(10)
        self.sb_pos_line_width.setObjectName("sb_pos_line_width")
        self.label_11 = QtWidgets.QLabel(self.groupBox_pos_cline)
        self.label_11.setGeometry(QtCore.QRect(20, 40, 41, 16))
        self.label_11.setObjectName("label_11")
        self.pb_pos_line_color = QtWidgets.QPushButton(self.groupBox_pos_cline)
        self.pb_pos_line_color.setGeometry(QtCore.QRect(120, 41, 41, 20))
        self.pb_pos_line_color.setStyleSheet("border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_pos_line_color.setObjectName("pb_pos_line_color")
        self.lv_pos_line = QtWidgets.QLabel(self.groupBox_pos_cline)
        self.lv_pos_line.setGeometry(QtCore.QRect(180, 10, 51, 51))
        self.lv_pos_line.setText("")
        self.lv_pos_line.setObjectName("lv_pos_line")
        self.label_15 = QtWidgets.QLabel(self.groupBox_pos_cline)
        self.label_15.setGeometry(QtCore.QRect(20, 18, 41, 16))
        self.label_15.setObjectName("label_15")
        self.cb_pos_line_style = QtWidgets.QComboBox(self.groupBox_pos_cline)
        self.cb_pos_line_style.setGeometry(QtCore.QRect(70, 18, 91, 20))
        self.cb_pos_line_style.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.cb_pos_line_style.setObjectName("cb_pos_line_style")
        self.cb_pos_line_style.addItem("")
        self.cb_pos_line_style.addItem("")
        self.cb_pos_line_style.addItem("")
        self.groupBox_pos_marker = QtWidgets.QGroupBox(phero_bg_info_setting)
        self.groupBox_pos_marker.setGeometry(QtCore.QRect(20, 240, 241, 87))
        self.groupBox_pos_marker.setStyleSheet("QGroupBox::indicator:unchecked{\n"
"    border: 1px solid rgb(100,100,100);\n"
"    background-color:rgb(100,100,100);\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid rgb(19, 126, 124);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.groupBox_pos_marker.setFlat(False)
        self.groupBox_pos_marker.setCheckable(True)
        self.groupBox_pos_marker.setChecked(False)
        self.groupBox_pos_marker.setObjectName("groupBox_pos_marker")
        self.cb_pos_marker = QtWidgets.QComboBox(self.groupBox_pos_marker)
        self.cb_pos_marker.setGeometry(QtCore.QRect(68, 20, 91, 21))
        self.cb_pos_marker.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.cb_pos_marker.setObjectName("cb_pos_marker")
        self.cb_pos_marker.addItem("")
        self.cb_pos_marker.addItem("")
        self.cb_pos_marker.addItem("")
        self.label_12 = QtWidgets.QLabel(self.groupBox_pos_marker)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 41, 16))
        self.label_12.setObjectName("label_12")
        self.pb_pos_marker_color = QtWidgets.QPushButton(self.groupBox_pos_marker)
        self.pb_pos_marker_color.setGeometry(QtCore.QRect(120, 40, 41, 35))
        self.pb_pos_marker_color.setStyleSheet("border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_pos_marker_color.setObjectName("pb_pos_marker_color")
        self.lv_pos_marker = QtWidgets.QLabel(self.groupBox_pos_marker)
        self.lv_pos_marker.setGeometry(QtCore.QRect(174, 18, 51, 51))
        self.lv_pos_marker.setText("")
        self.lv_pos_marker.setObjectName("lv_pos_marker")
        self.label_13 = QtWidgets.QLabel(self.groupBox_pos_marker)
        self.label_13.setGeometry(QtCore.QRect(20, 42, 41, 16))
        self.label_13.setObjectName("label_13")
        self.sb_pos_marker_width = QtWidgets.QSpinBox(self.groupBox_pos_marker)
        self.sb_pos_marker_width.setGeometry(QtCore.QRect(68, 42, 41, 16))
        self.sb_pos_marker_width.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.sb_pos_marker_width.setMaximum(100)
        self.sb_pos_marker_width.setProperty("value", 2)
        self.sb_pos_marker_width.setDisplayIntegerBase(10)
        self.sb_pos_marker_width.setObjectName("sb_pos_marker_width")
        self.label_17 = QtWidgets.QLabel(self.groupBox_pos_marker)
        self.label_17.setGeometry(QtCore.QRect(20, 62, 41, 16))
        self.label_17.setObjectName("label_17")
        self.sb_pos_marker_radius = QtWidgets.QSpinBox(self.groupBox_pos_marker)
        self.sb_pos_marker_radius.setGeometry(QtCore.QRect(66, 62, 41, 16))
        self.sb_pos_marker_radius.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.sb_pos_marker_radius.setMinimum(10)
        self.sb_pos_marker_radius.setMaximum(200)
        self.sb_pos_marker_radius.setProperty("value", 20)
        self.sb_pos_marker_radius.setDisplayIntegerBase(10)
        self.sb_pos_marker_radius.setObjectName("sb_pos_marker_radius")
        self.pb_ok = QtWidgets.QPushButton(phero_bg_info_setting)
        self.pb_ok.setGeometry(QtCore.QRect(180, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_ok.setFont(font)
        self.pb_ok.setStyleSheet("border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_ok.setObjectName("pb_ok")
        self.pb_cancel = QtWidgets.QPushButton(phero_bg_info_setting)
        self.pb_cancel.setGeometry(QtCore.QRect(90, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_cancel.setFont(font)
        self.pb_cancel.setStyleSheet("border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_cancel.setObjectName("pb_cancel")
        self.label_14 = QtWidgets.QLabel(phero_bg_info_setting)
        self.label_14.setGeometry(QtCore.QRect(20, 0, 231, 20))
        self.label_14.setObjectName("label_14")
        self.te_select_id = QtWidgets.QTextEdit(phero_bg_info_setting)
        self.te_select_id.setGeometry(QtCore.QRect(20, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.te_select_id.setFont(font)
        self.te_select_id.setStyleSheet("border:1px solid rgb(19, 126, 124);\n"
"color:rgb(255, 255, 127)")
        self.te_select_id.setObjectName("te_select_id")
        self.groupBox_arena_border = QtWidgets.QGroupBox(phero_bg_info_setting)
        self.groupBox_arena_border.setGeometry(QtCore.QRect(20, 338, 241, 71))
        self.groupBox_arena_border.setStyleSheet("QGroupBox::indicator:unchecked{\n"
"    border: 1px solid rgb(100,100,100);\n"
"    background-color:rgb(100,100,100);\n"
"}\n"
"QGroupBox{\n"
"    border: 1px solid rgb(19, 126, 124);\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.groupBox_arena_border.setFlat(False)
        self.groupBox_arena_border.setCheckable(True)
        self.groupBox_arena_border.setChecked(False)
        self.groupBox_arena_border.setObjectName("groupBox_arena_border")
        self.pb_arena_border_color = QtWidgets.QPushButton(self.groupBox_arena_border)
        self.pb_arena_border_color.setGeometry(QtCore.QRect(120, 40, 41, 21))
        self.pb_arena_border_color.setStyleSheet("border: 2px solid rgb(19, 126, 124);\n"
"border-radius:10px;")
        self.pb_arena_border_color.setObjectName("pb_arena_border_color")
        self.lv_arena_border = QtWidgets.QLabel(self.groupBox_arena_border)
        self.lv_arena_border.setGeometry(QtCore.QRect(180, 10, 51, 51))
        self.lv_arena_border.setText("")
        self.lv_arena_border.setObjectName("lv_arena_border")
        self.label_20 = QtWidgets.QLabel(self.groupBox_arena_border)
        self.label_20.setGeometry(QtCore.QRect(20, 41, 41, 21))
        self.label_20.setObjectName("label_20")
        self.sb_arena_border_width = QtWidgets.QSpinBox(self.groupBox_arena_border)
        self.sb_arena_border_width.setGeometry(QtCore.QRect(60, 44, 51, 16))
        self.sb_arena_border_width.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.sb_arena_border_width.setMaximum(100)
        self.sb_arena_border_width.setProperty("value", 2)
        self.sb_arena_border_width.setDisplayIntegerBase(10)
        self.sb_arena_border_width.setObjectName("sb_arena_border_width")
        self.label_21 = QtWidgets.QLabel(self.groupBox_arena_border)
        self.label_21.setGeometry(QtCore.QRect(20, 10, 41, 31))
        self.label_21.setObjectName("label_21")
        self.sb_arena_border_margin = QtWidgets.QSpinBox(self.groupBox_arena_border)
        self.sb_arena_border_margin.setGeometry(QtCore.QRect(70, 20, 91, 16))
        self.sb_arena_border_margin.setStyleSheet("border: 2px soild rgb(19, 126, 124);\n"
"color: rgb(255, 255, 127);\n"
"")
        self.sb_arena_border_margin.setMaximum(100)
        self.sb_arena_border_margin.setProperty("value", 2)
        self.sb_arena_border_margin.setDisplayIntegerBase(10)
        self.sb_arena_border_margin.setObjectName("sb_arena_border_margin")

        self.retranslateUi(phero_bg_info_setting)
        self.cb_pos_line_style.setCurrentIndex(0)
        self.cb_pos_marker.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(phero_bg_info_setting)

    def retranslateUi(self, phero_bg_info_setting):
        _translate = QtCore.QCoreApplication.translate
        phero_bg_info_setting.setWindowTitle(_translate("phero_bg_info_setting", "Form"))
        self.groupBox_pos_text.setTitle(_translate("phero_bg_info_setting", "Position Text"))
        self.pb_pos_text_color.setText(_translate("phero_bg_info_setting", "Color"))
        self.label_16.setText(_translate("phero_bg_info_setting", "Width"))
        self.groupBox_pos_cline.setTitle(_translate("phero_bg_info_setting", "Position Cross Line"))
        self.label_11.setText(_translate("phero_bg_info_setting", "Width"))
        self.pb_pos_line_color.setText(_translate("phero_bg_info_setting", "Color"))
        self.label_15.setText(_translate("phero_bg_info_setting", "Style"))
        self.cb_pos_line_style.setItemText(0, _translate("phero_bg_info_setting", "solid"))
        self.cb_pos_line_style.setItemText(1, _translate("phero_bg_info_setting", "dashed"))
        self.cb_pos_line_style.setItemText(2, _translate("phero_bg_info_setting", "dotted"))
        self.groupBox_pos_marker.setTitle(_translate("phero_bg_info_setting", "Position Marker"))
        self.cb_pos_marker.setItemText(0, _translate("phero_bg_info_setting", "circle"))
        self.cb_pos_marker.setItemText(1, _translate("phero_bg_info_setting", "square"))
        self.cb_pos_marker.setItemText(2, _translate("phero_bg_info_setting", "triangle"))
        self.label_12.setText(_translate("phero_bg_info_setting", "Marker"))
        self.pb_pos_marker_color.setText(_translate("phero_bg_info_setting", "Color"))
        self.label_13.setText(_translate("phero_bg_info_setting", "Width"))
        self.label_17.setText(_translate("phero_bg_info_setting", "Radius"))
        self.pb_ok.setText(_translate("phero_bg_info_setting", "OK"))
        self.pb_cancel.setText(_translate("phero_bg_info_setting", "Cancel"))
        self.label_14.setText(_translate("phero_bg_info_setting", "Type ID that show the info"))
        self.te_select_id.setToolTip(_translate("phero_bg_info_setting", "<html><head/><body><p>Define robot <span style=\" font-weight:600;\">ID,</span><span style=\" font-style:italic;\">e.g.: 0,1,2,all</span></p></body></html>"))
        self.groupBox_arena_border.setTitle(_translate("phero_bg_info_setting", "Arena Border"))
        self.pb_arena_border_color.setText(_translate("phero_bg_info_setting", "Color"))
        self.label_20.setText(_translate("phero_bg_info_setting", "Width"))
        self.label_21.setText(_translate("phero_bg_info_setting", "Margin"))
